name: shastamcbride
favicon: null
layout_spectrum: 0.75214
typography_spectrum: 0.84767
title: Shasta McBride
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a0bad1'
    - '#e52938'
    - '#625f71'
    - '#342a24'
    - '#cb839f'
  brandStrength: 0.48906716681085527
  lightness: 1
  saturation: 0.625
  rhythmicContrast: 0.8698934621643275
purpose: []
