name: shastamcbride
favicon: null
layout_spectrum: 0.6019295146688819
typography_spectrum: 0.28021897468715906
title: Shasta McBride
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.48906716681085527
  lightness: 0.6614348464645445
  saturation: 0.31389298429712653
  rhythmicContrast: 0.8698934621643275
purpose: []
